// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

// AdvertisementsSync defines model for AdvertisementsSync.
type AdvertisementsSync struct {
	Message string `json:"message"`
}

// StartGASPSync defines model for StartGASPSync.
type StartGASPSync struct {
	Message string `json:"message"`
}

// AdvertisementsSyncResponse defines model for AdvertisementsSyncResponse.
type AdvertisementsSyncResponse = AdvertisementsSync

// StartGASPSyncResponse defines model for StartGASPSyncResponse.
type StartGASPSyncResponse = StartGASPSync
