// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

// ArcIngestBody defines model for ArcIngestBody.
type ArcIngestBody struct {
	// BlockHeight Block height where the transaction was included
	BlockHeight uint32 `json:"blockHeight"`

	// MerklePath Merkle path in hexadecimal format
	MerklePath string `json:"merklePath"`

	// Txid Transaction ID in hexadecimal format
	Txid string `json:"txid"`
}

// LookupQuestionBody defines model for LookupQuestionBody.
type LookupQuestionBody struct {
	// Query Query parameters specific to the service
	Query map[string]interface{} `json:"query"`

	// Service Service name to query
	Service string `json:"service"`
}

// RequestForeignGASPNodeBody defines model for RequestForeignGASPNodeBody.
type RequestForeignGASPNodeBody struct {
	// GraphID The graph ID in the format of "txid.outputIndex"
	GraphID string `json:"graphID"`

	// OutputIndex The output index
	OutputIndex uint32 `json:"outputIndex"`

	// Txid The transaction ID
	Txid string `json:"txid"`
}

// RequestSyncResponseBody defines model for RequestSyncResponseBody.
type RequestSyncResponseBody struct {
	// Limit Maximum number of items to return
	Limit uint32 `json:"limit"`

	// Since Timestamp or sequence number from which to start synchronization
	Since float64 `json:"since"`

	// Version The version number of the GASP protocol
	Version int `json:"version"`
}
