// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

// AdmittanceInstructions defines model for AdmittanceInstructions.
type AdmittanceInstructions struct {
	AncillaryTxIDs []string `json:"ancillaryTxIDs"`
	CoinsRemoved   []uint32 `json:"coinsRemoved"`
	CoinsToRetain  []uint32 `json:"coinsToRetain"`
	OutputsToAdmit []uint32 `json:"outputsToAdmit"`
}

// ArcIngest defines model for ArcIngest.
type ArcIngest struct {
	Message string `json:"message"`
	Status  string `json:"status"`
}

// GASPNode A GASP node representation from the overlay engine
type GASPNode struct {
	// GraphID The graph ID of the GASP node
	GraphID string `json:"graphID"`

	// Inputs The inputs of the GASP node
	Inputs map[string]interface{} `json:"inputs"`

	// OutputIndex The output index of the GASP node
	OutputIndex uint32 `json:"outputIndex"`

	// OutputMetadata The metadata of the GASP node
	OutputMetadata string `json:"outputMetadata"`

	// Proof The proof of the GASP node
	Proof string `json:"proof"`

	// RawTx The raw transaction of the GASP node
	RawTx string `json:"rawTx"`

	// TxMetadata The metadata of the GASP node
	TxMetadata string `json:"txMetadata"`
}

// LookupAnswer defines model for LookupAnswer.
type LookupAnswer struct {
	Outputs []OutputListItem `json:"outputs"`
	Result  string           `json:"result"`
	Type    string           `json:"type"`
}

// LookupServiceDocumentation defines model for LookupServiceDocumentation.
type LookupServiceDocumentation struct {
	// Documentation Markdown-formatted documentation for the lookup service
	Documentation string `json:"documentation"`
}

// Metadata defines model for Metadata.
type Metadata map[string]ServiceMetadata

// OutputListItem defines model for OutputListItem.
type OutputListItem struct {
	Beef        []byte `json:"beef"`
	OutputIndex uint32 `json:"outputIndex"`
}

// RequestSyncRes defines model for RequestSyncRes.
type RequestSyncRes struct {
	UTXOList []UTXOItem `json:"UTXOList"`

	// Since Timestamp or sequence number from which synchronization data was generated
	Since float64 `json:"since"`
}

// STEAK defines model for STEAK.
type STEAK map[string]AdmittanceInstructions

// ServiceMetadata defines model for ServiceMetadata.
type ServiceMetadata struct {
	IconURL          string `json:"iconURL"`
	InformationURL   string `json:"informationURL"`
	Name             string `json:"name"`
	ShortDescription string `json:"shortDescription"`
	Version          string `json:"version"`
}

// SubmitTransaction defines model for SubmitTransaction.
type SubmitTransaction struct {
	STEAK STEAK `json:"STEAK"`
}

// TopicManagerDocumentation defines model for TopicManagerDocumentation.
type TopicManagerDocumentation struct {
	// Documentation Markdown-formatted documentation for the topic manager
	Documentation string `json:"documentation"`
}

// UTXOItem defines model for UTXOItem.
type UTXOItem struct {
	// OutputIndex Output index number
	OutputIndex int `json:"outputIndex"`

	// Score Sort score of the UTXO, used for prioritization in synchronization
	Score float64 `json:"score"`

	// Txid Transaction ID in hexadecimal format
	Txid string `json:"txid"`
}

// ArcIngestResponse defines model for ArcIngestResponse.
type ArcIngestResponse = ArcIngest

// LookupQuestionResponse defines model for LookupQuestionResponse.
type LookupQuestionResponse = LookupAnswer

// LookupServiceProviderDocumentationResponse defines model for LookupServiceProviderDocumentationResponse.
type LookupServiceProviderDocumentationResponse = LookupServiceDocumentation

// MetadataResponse defines model for MetadataResponse.
type MetadataResponse = Metadata

// RequestForeignGASPNodeResponse A GASP node representation from the overlay engine
type RequestForeignGASPNodeResponse = GASPNode

// RequestSyncResResponse defines model for RequestSyncResResponse.
type RequestSyncResResponse = RequestSyncRes

// SubmitTransactionResponse defines model for SubmitTransactionResponse.
type SubmitTransactionResponse = SubmitTransaction

// TopicManagerDocumentationResponse defines model for TopicManagerDocumentationResponse.
type TopicManagerDocumentationResponse = TopicManagerDocumentation
