// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: auth_fetch.proto

package typescript

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthFetch_Fetch_FullMethodName   = "/typescript.AuthFetch/fetch"
	AuthFetch_CleanUp_FullMethodName = "/typescript.AuthFetch/cleanUp"
)

// AuthFetchClient is the client API for AuthFetch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthFetchClient interface {
	Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error)
	CleanUp(ctx context.Context, in *CleanUpRequest, opts ...grpc.CallOption) (*CleanUpResponse, error)
}

type authFetchClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthFetchClient(cc grpc.ClientConnInterface) AuthFetchClient {
	return &authFetchClient{cc}
}

func (c *authFetchClient) Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchResponse)
	err := c.cc.Invoke(ctx, AuthFetch_Fetch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authFetchClient) CleanUp(ctx context.Context, in *CleanUpRequest, opts ...grpc.CallOption) (*CleanUpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CleanUpResponse)
	err := c.cc.Invoke(ctx, AuthFetch_CleanUp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthFetchServer is the server API for AuthFetch service.
// All implementations must embed UnimplementedAuthFetchServer
// for forward compatibility.
type AuthFetchServer interface {
	Fetch(context.Context, *FetchRequest) (*FetchResponse, error)
	CleanUp(context.Context, *CleanUpRequest) (*CleanUpResponse, error)
	mustEmbedUnimplementedAuthFetchServer()
}

// UnimplementedAuthFetchServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthFetchServer struct{}

func (UnimplementedAuthFetchServer) Fetch(context.Context, *FetchRequest) (*FetchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fetch not implemented")
}

func (UnimplementedAuthFetchServer) CleanUp(context.Context, *CleanUpRequest) (*CleanUpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CleanUp not implemented")
}
func (UnimplementedAuthFetchServer) mustEmbedUnimplementedAuthFetchServer() {}
func (UnimplementedAuthFetchServer) testEmbeddedByValue()                   {}

// UnsafeAuthFetchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthFetchServer will
// result in compilation errors.
type UnsafeAuthFetchServer interface {
	mustEmbedUnimplementedAuthFetchServer()
}

func RegisterAuthFetchServer(s grpc.ServiceRegistrar, srv AuthFetchServer) {
	// If the following call pancis, it indicates UnimplementedAuthFetchServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthFetch_ServiceDesc, srv)
}

func _AuthFetch_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthFetchServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthFetch_Fetch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthFetchServer).Fetch(ctx, req.(*FetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthFetch_CleanUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthFetchServer).CleanUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthFetch_CleanUp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthFetchServer).CleanUp(ctx, req.(*CleanUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthFetch_ServiceDesc is the grpc.ServiceDesc for AuthFetch service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthFetch_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "typescript.AuthFetch",
	HandlerType: (*AuthFetchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "fetch",
			Handler:    _AuthFetch_Fetch_Handler,
		},
		{
			MethodName: "cleanUp",
			Handler:    _AuthFetch_CleanUp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth_fetch.proto",
}
