# This script was generated by Taurus

from gevent import sleep
from re import findall, compile
from locust import HttpUser, TaskSet, task, constant

class UserBehaviour(TaskSet):
    @task(1)
    def generated_task(self):
        self.client.get(headers={"Accept": "application/json", "Authorization": "mainnet_2975d2afeb0b46f9e249f035949e700a"}, timeout=5.0, url="https://api-ovh.whatsonchain.com/v1/bsv/main/address/18VWHjMt4ixHddPPbs6righWTs3Sg2QNcn/balance")


class GeneratedSwarm(HttpUser):
    tasks = [UserBehaviour]
    host = ""
    wait_time = constant(0)

