name: WoC Go App Build

on: workflow_dispatch
#on:
#  push:
#    branches: [master]
#  pull_request:
#    branches: [master]

jobs:
  build:
    name: Build Go Project
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: 'https://hooks.slack.com/services/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'
      GOOS: linux
      GOARCH: amd64
      GO114MODULE: 'on'
      GOPRIVATE: 'github.com/teranode-group'
      CGO_ENABLED: 0
      DEBUG: 1
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.4' 

    - name: Go Configuration
      run: |
        git config --global --add url."git@github.com:".insteadOf "https://github.com/"
        # Generate GITHUB_ENV Variables
        PROG_NAME=$(awk -F'"' '/^const progname =/ {print $2}' main.go)
        GITHUB_SHA_HASH=${{ github.sha }}
        GIT_COMMIT_SHORT=${GITHUB_SHA_HASH:0:7}
        FILE_NAME="${PROG_NAME}_${GIT_COMMIT_SHORT}_${{ github.run_number }}"
        # Set GITHUB_ENV Variables
        echo "PROG_NAME=${PROG_NAME}" >> $GITHUB_ENV
        echo "GIT_COMMIT_SHORT=${GIT_COMMIT_SHORT}" >> $GITHUB_ENV
        echo "FILE_NAME=${FILE_NAME}" >> $GITHUB_ENV
          
    - name: Building
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.WOC_SSH_KEY }}"
        echo "Building program name ${{ env.PROG_NAME }}"
        echo "with short commit version ${{ env.GIT_COMMIT_SHORT }}"
        echo "using file name ${{ env.FILE_NAME }} ..."
        echo ${{ env.DEBUG }}
        echo ${{ env.CGO_ENABLED }}
        go version
        mkdir -p build/linux
        mkdir -p build_tar/${{ env.PROG_NAME }}
        ls -lrtah
        if [[ ${{ env.DEBUG }} == "1" ]]; then
            echo "debug build..."
            go build --trimpath \
            -o build/linux/${{ env.FILE_NAME }} \
            -ldflags="-extldflags '-static' -s -w -X main.commit=${{ env.GIT_COMMIT_SHORT }} -X main.version=MANUAL" \
            -gcflags "all=-N -l"
        else
            go build  --trimpath \
            -o build/linux/${{ env.FILE_NAME }} \
            -ldflags="-extldflags '-static' -s -w -X main.commit=${{ env.GIT_COMMIT_SHORT }} -X main.version=MANUAL"
        fi
      
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock

    - name: Archive build
      run: |
        cp settings_local.conf build/linux/
        cd build/linux/ 
        tar cvfz ${{ env.FILE_NAME }}.tar.gz settings_local.conf ${{ env.FILE_NAME }}

    - name: Slack Notification on Failure
      if: failure()
      run: |
        curl -X POST -H 'Content-type: application/json' \
            --data '{
              "text": ":x: *Build Failed!* :boom:\n• *Repo:* '"${{ github.repository }}"'\n•  *Run:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View logs>"
            }' \
            ${{ env.SLACK_WEBHOOK_URL }}

    - name: Slack Notification on Success
      if: success()
      run: |
        curl -X POST -H 'Content-type: application/json' \
            --data '{
              "text": ":white_check_mark: *Build Succeeded!*\n• *Repo:* '"${{ github.repository }}"'\n•  *Run:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View logs>"
            }' \
            ${{ env.SLACK_WEBHOOK_URL }} 
